### ISSUE TITLE
Connecting to database on the same machine fails

### ISSUE THREAD

**Issue by tvrprasad** [tvrprasad/sspi-client#15]
Connecting to database on a different machine is working with Tedious hack integration - https://github.com/tvrprasad/tedious/tree/windows-integrated-auth-draft

Connecting to the same machine seems to fail.

NTLM Login7: data
NTLM Login7: message
NTLM Login7: receivedChallenge
NTLM Reseponse: data
buffer.js:816
    throw new RangeError('Index out of range');
    ^

RangeError: Index out of range
    at checkOffset (buffer.js:816:11)
    at Buffer.readInt16LE (buffer.js:951:5)
    at parseChallenge (E:\src\tedious\src\token\sspi-token-parser.js:13:32)
    at parser.readUsVarByte (E:\src\tedious\src\token\sspi-token-parser.js:27:19)
    at awaitData (E:\src\tedious\src\token\stream-parser.js:316:7)
    at Parser.awaitData (E:\src\tedious\src\token\stream-parser.js:100:7)
    at Parser.readBuffer (E:\src\tedious\src\token\stream-parser.js:313:10)
    at readUInt16LE (E:\src\tedious\src\token\stream-parser.js:348:12)
    at awaitData (E:\src\tedious\src\token\stream-parser.js:144:7)
    at Parser.awaitData (E:\src\tedious\src\token\stream-parser.js:100:7)

```JavaScript
var config= {
  userName: 'venktam',
  domain: 'REDMOND',
  password: '',
  server: 'prasadtammana',
  options: { encrypt: false, database: 'AdventureWorks2016CTP3' }
};

var connection = new Connection(config);
connection.on('connect', function (err) {
  if (err) {
    console.log("Connection failed. Error details:");
    console.log(err);
  }
  else {
    console.log("Connected");
    connection.close();
  }
});
```

**Comment by tvrprasad** [comment]
Further testing shows that the failure above, on the same machine, happens only for 'negotiate' security package. Connection establishment succeeds for 'ntlm' and 'kerberos'.

**Comment by tvrprasad** [comment]
Windows SSPI API design allows for arbitrary number of round trips to complete authentication where the Tedious code is currently written to handle only one-round trip. So far this worked on all cases except 'negotiate'

There is an extra round trip with the server when using the 'negotiate' securityPackage on the same machine. When this happens Tedious is processing the incoming stream while in a wrong state.
